"""empty message

Revision ID: 1c49b0456639
Revises: da4e6607bfc4
Create Date: 2019-10-30 15:25:59.806766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c49b0456639'
down_revision = 'da4e6607bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')

    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
